/**
 * FHIR Bundle → PhpData mapper.
 * Reads a PCO IG collection Bundle (as generated by fhir-builder.ts)
 * and reconstructs a PhpData object suitable for PDF generation.
 *
 * Fields not represented in the bundle (values, vision, strengths,
 * discharge_plan, is_final_session) will be absent from the PDF.
 */

import type { PhpData, Patient, WbsAssessment, Goal } from "../models.js";

// ---------------------------------------------------------------------------
// Constants (mirrors fhir-builder.ts)
// ---------------------------------------------------------------------------

const SNOMED_SYSTEM = "http://snomed.info/sct";
const WHAT_MATTERS_CODE = "247751003";
const WBS_SYSTEM = "http://mtnlotus.com/fhir/whole-health-cards/CodeSystem/well-being-signs";
const WBS_PANEL_CODE = "well-being-signs";
const PCO_READINESS_PROFILE = "http://hl7.org/fhir/us/pco/StructureDefinition/pco-readiness-assessment";
const GOAL_TYPE_SYSTEM = "http://mtnlotus.com/fhir/whole-health-cards/CodeSystem/goal-type";

// ---------------------------------------------------------------------------
// Minimal structural types for reading bundle JSON
// ---------------------------------------------------------------------------

interface Coding { system?: string; code?: string }
interface CodeableConcept { coding?: Coding[]; text?: string }
interface Component { code: CodeableConcept; valueInteger?: number }
interface Annotation { text: string }
interface HumanName { family?: string; given?: string[] }
interface Extension { url: string; valueReference?: { reference: string } }
interface Period { start?: string; end?: string }
interface Reference { reference: string }

interface BundleResource {
  resourceType: string;
  meta?: { profile?: string[] };
  // Patient
  name?: HumanName[];
  birthDate?: string;
  // Observation
  code?: CodeableConcept;
  subject?: Reference;
  focus?: Reference[];
  effectiveDateTime?: string;
  valueString?: string;
  component?: Component[];
  note?: Annotation[];
  // Goal
  lifecycleStatus?: string;
  description?: { text: string };
  startDate?: string;
  category?: { coding?: { system?: string; code?: string }[] }[];
}

interface BundleEntry {
  fullUrl: string;
  resource: BundleResource;
}

export interface FhirBundle {
  resourceType: "Bundle";
  type: string;
  entry: BundleEntry[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse the MAP Observation valueString back into structured fields.
 * The builder encodes: "Mission: X Aspiration: Y Purpose: Z narrative"
 * When no labeled fields are present, the whole string is what_matters_most.
 */
function parseMapValueString(text: string): {
  map?: { mission?: string; aspiration?: string; purpose?: string };
  what_matters_most?: string;
} {
  const hasMission    = /Mission:/i.test(text);
  const hasAspiration = /Aspiration:/i.test(text);
  const hasPurpose    = /Purpose:/i.test(text);

  if (!hasMission && !hasAspiration && !hasPurpose) {
    return { what_matters_most: text };
  }

  // Extract each labeled segment; each runs until the next label or end of string
  const mission    = text.match(/Mission:\s*(.*?)(?=\s+Aspiration:|\s+Purpose:|$)/si)?.[1]?.trim();
  const aspiration = text.match(/Aspiration:\s*(.*?)(?=\s+Purpose:|$)/si)?.[1]?.trim();
  // Purpose runs to end; we can't separate it from a trailing narrative
  const purpose    = text.match(/Purpose:\s*(.*)/si)?.[1]?.trim();

  const map = (mission || aspiration || purpose)
    ? { mission, aspiration, purpose }
    : undefined;

  return { map };
}

// ---------------------------------------------------------------------------
// Bundle → PhpData
// ---------------------------------------------------------------------------

/**
 * Reconstruct a PhpData object from a FHIR Bundle generated by fhir-builder.ts.
 *
 * Fields not encoded in the bundle (values, vision, strengths, discharge_plan,
 * is_final_session) are omitted and the corresponding PDF sections will be blank.
 */
export function bundleToPhpData(bundle: FhirBundle): PhpData {
  const entries = bundle.entry ?? [];

  // Index entries by fullUrl for reference resolution
  const byUrl = new Map<string, BundleResource>();
  for (const e of entries) {
    byUrl.set(e.fullUrl, e.resource);
  }

  let patient: Patient | undefined;
  let sessionDate: string | undefined;
  let map: PhpData["map"] | undefined;
  let what_matters_most: string | undefined;
  let wbs: WbsAssessment | undefined;

  // Goals are indexed by fullUrl so Readiness and ServiceRequest can reference them.
  const goals: Goal[] = [];
  const goalIdxByUrl = new Map<string, number>();

  // Pass 1 — Goals (must be indexed before Observation/ServiceRequest references)
  for (const entry of entries) {
    const r = entry.resource;
    if (r.resourceType === "Goal") {
      const goalTypeCoding = r.category
        ?.flatMap((c) => c.coding ?? [])
        .find((c) => c.system === GOAL_TYPE_SYSTEM);
      const goalType = goalTypeCoding?.code === "short-term" ? "short-term" : "long-term";
      const goal: Goal = {
        text: r.description?.text ?? "",
        goal_type: goalType,
        lifecycle_status: r.lifecycleStatus ?? "active",
        start_date: r.startDate,
      };
      goalIdxByUrl.set(entry.fullUrl, goals.length);
      goals.push(goal);
    }
  }

  // Pass 2 — Patient, Observations, ServiceRequests
  for (const entry of entries) {
    const r = entry.resource;

    if (r.resourceType === "Patient") {
      const name = r.name?.[0];
      patient = {
        family: name?.family ?? "",
        given: name?.given ?? [],
        birth_date: r.birthDate,
      };
    }

    else if (r.resourceType === "Observation") {
      const isReadiness = r.meta?.profile?.includes(PCO_READINESS_PROFILE);
      const codeSystem  = r.code?.coding?.[0]?.system;
      const codeCode    = r.code?.coding?.[0]?.code;

      if (isReadiness) {
        // Attach readiness scores and rationale to the referenced goal.
        // Most-recent-wins: later observations overwrite earlier ones.
        const goalUrl = r.focus?.[0]?.reference;
        const goalIdx = goalUrl !== undefined ? goalIdxByUrl.get(goalUrl) : undefined;
        if (goalIdx !== undefined) {
          const goal = goals[goalIdx];
          for (const comp of r.component ?? []) {
            const code = comp.code.coding?.[0]?.code;
            if (code === "importance" && comp.valueInteger !== undefined) goal.importance = comp.valueInteger;
            if (code === "confidence" && comp.valueInteger !== undefined) goal.confidence = comp.valueInteger;
          }
          const notes = r.note ?? [];
          if (notes[0]) goal.importance_note = notes[0].text;
          if (notes[1]) goal.confidence_note = notes[1].text;
        }
        if (r.effectiveDateTime && !sessionDate) sessionDate = r.effectiveDateTime.slice(0, 10);
      }

      else if (codeSystem === SNOMED_SYSTEM && codeCode === WHAT_MATTERS_CODE) {
        // MAP / Sense of Purpose observation. Most-recent-wins across notes.
        if (r.effectiveDateTime) sessionDate = r.effectiveDateTime.slice(0, 10);
        if (r.valueString) {
          const parsed = parseMapValueString(r.valueString);
          if (parsed.map) map = parsed.map;
          if (parsed.what_matters_most) what_matters_most = parsed.what_matters_most;
        }
      }

      else if (codeSystem === WBS_SYSTEM && codeCode === WBS_PANEL_CODE) {
        // WBS panel — last occurrence in the bundle is the most recent session.
        const wbsObj: Partial<WbsAssessment> = {};
        if (r.effectiveDateTime) {
          wbsObj.session_date = r.effectiveDateTime.slice(0, 10);
          sessionDate = wbsObj.session_date;
        }
        for (const comp of r.component ?? []) {
          const code = comp.code.coding?.[0]?.code;
          if (code === "satisfied"   && comp.valueInteger !== undefined) wbsObj.satisfied   = comp.valueInteger;
          if (code === "involved"    && comp.valueInteger !== undefined) wbsObj.involved    = comp.valueInteger;
          if (code === "functioning" && comp.valueInteger !== undefined) wbsObj.functioning = comp.valueInteger;
        }
        const scores = [wbsObj.satisfied, wbsObj.involved, wbsObj.functioning]
          .filter((s): s is number => s !== undefined);
        if (scores.length) {
          wbsObj.average = Math.round((scores.reduce((a, b) => a + b, 0) / scores.length) * 100) / 100;
        }
        wbs = wbsObj as WbsAssessment;
      }
    }

  }

  return {
    patient,
    session_date: sessionDate,
    what_matters_most,
    map,
    values: [],
    vision: undefined,
    strengths: [],
    wbs,
    goals,
    is_final_session: false,
    discharge_plan: undefined,
  };
}
